### ISSUE TITLE
[Feature Request] Support for HTTP CONNECT proxies

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#591] opened 2023-08-16 15:15 UTC
### Describe the solution you'd like
People need to be able to supply a `HTTP CONNECT` proxy to the client. Tonic/hyper doesn't have native support, but there is [a library](https://github.com/tafia/hyper-proxy) and a [sample](https://github.com/hyperium/hyper/blob/master/examples/http_proxy.rs).

**Comment by josh-berry** [comment] 2024-03-27 01:06
Duplicate of #309

**Closed by josh-berry** 2024-03-27 01:06 UTC
Labels: enhancement
