### ISSUE TITLE
[Bug] `updateSearchAttribute` with an non-existant attribute cause hard to diagnose `WFTTimedOut`

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-core#521] opened 2023-03-28 22:12 UTC
### Describe the bug

In a workflow, calling `updateSearchAttribute` with an non-existant attribute cause the server to refuse the WFTCompletion with gRPC status 3 (ie. `InvalidArgument`) and message `Namespace default has no mapping defined for search attribute <search attribute name>`.

From a user perspective, what happens at that point is:

1. Core logs the following message at warn level:

```
Network error while completing workflow activation
```

2. In Workflow history, the workflow is stuck with a `WorkflowTaskTimedOut`
3. The WFT is being replayed in loop

Note that none of the above will help the user understand why his workflow is blocked. Only if the user has access to the server's log (which is not the case in TCloud and probably difficult to reach in most production setup) will he find out the following error message:

```
{"level":"info","ts":"...","msg":"history client encountered error","service":"frontend","error":"Namespace default has no mapping defined for search attribute <search attribute name>","service-error-type":"serviceerror.InvalidArgument","logging-call-at":"metric_client.go:90"}
```

We really need to find a way to make these kind of errors easier to diagnose for users.

### Expected behaviour

Core should probably include the incoming gRPC error message into the reported warning (see [pertinent code](https://github.com/temporalio/sdk-core/blob/master/core/src/worker/workflow/mod.rs#L545-L556)). Assuming that Workflow Workers' logs are accessible to the developper (which is much more likely than them having access to server's log), this would provide better visibility on the cause of the failure.

Another thing to be considered (not sure if possible) would be to have the worker report a WFTFailure to the server if it receives a user-need-to-be-aware error to its `WFTCompletedRequest`.

**Comment by Sushisource** [comment] 2023-03-28 22:56
@mjameswh Including the grpc message in the error is easy and I'll do that - reporting the WFT failure seems wrong for us to need to do SDK side. Server could/should just fail the workflow task itself in this specific case, seemingly.

**Comment by dandavison** [comment] 2023-07-21 23:35
I tried thinking this one through. I'm finding myself coming to a conclusion similar to @mjameswh -- I'm thinking that the best solution would be for the SDK to fail the workflow execution. I don't think it's the server's responsibility to fail it because the server has to allow for the possibility that the SDK will send a second completion request with valid input. Here's my thinking:

#### Facts
- `upsertSearchAttribute` can be called from a workflow.
- The requested attributes are included in the WFTCompletion.
- The requested attributes may be invalid (by design)
- If a user calls `upsertSearchAttribute` with an invalid attribute then Frontend [refuses](https://github.com/temporalio/temporal/blob/e10f21389014a9634d534e9e1453662b68f46272/common/namespace/namespace.go#L329) to accept the WFTCompletion
- That causes a WorkflowTaskTimedOut event
- The worker retries (? If it does, it shouldn’t, because the server response is saying invalid input, which shouldn’t be retried by a client)
- The workflow will not progress further.

#### Core problem
The user needs to understand why their workflow is not progressing and how to fix the situation.

#### Solution
How should we help the user? What does the user need to do to fix the situation?

They need to modify and redeploy their workflow code so that it no longer requests invalid search attributes; existing wf executions that are blocked due to this problem will need to be canceled/terminated.

Therefore the most helpful outcome for the user would be for the workflow to report a failure in their application code with a helpful error message:  the workflow execution is going to need to be terminated anyway, and an error in their application code is a more direct way for them to be alerted to the problem than a workflow that never makes progress, causing them to need to look at worker logs to understand why.

That suggests that the SDK should send a `FailWorkflowExecution` command to the server when it receives the InvalidArgument response from Frontend.

**Comment by Sushisource** [comment] 2023-07-22 00:09
I think this is mostly right - though we don't want to fail the whole workflow, rather we want to fail the workflow task.

I'm fine with the SDK being the one that initiates the failure. In principle,. this is unnecessary, since server has all the information and we can obtain the same outcome. However, there is one important reason that it probably makes sense to do it SDK side, which is we have existing mechanisms that avoid spamming WFT failures in the event we're encountering that same failure over and over. (Though, thinking about it, server could handle that case here too, but this is code we already have written in SDK).

So I'm fine proceeding with making this fail the WFT from the SDK side with a reasonable message.

**Comment by Sushisource** [comment] 2023-07-24 16:39
@dandavison Cool, so looks like they went with my original idea serve side. Works for me.

**Comment by dandavison** [comment] 2023-07-24 17:27
OK thanks all, closing this.

**Closed by dandavison** 2023-07-24 17:27 UTC
Labels: bug
